name: Scrape Kings League Infojobs Website

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
      
  schedule:
    - cron: "0 */1 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18      
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
          run_install: true
      - run: |
          node scraping/leaderboard.js
          git diff --quiet && git diff --staged --quiet || git commit -am "Update Kings League database"
          git push origin main
